Repository acsone/alfodoo, pull requests merged in 2024-06, with the labels that each got.

#179 [16.0][MIG] cmis_web_bus - Migration to 16.0
  .pre-commit-config.yaml
  cmis_web_bus/README.rst
  cmis_web_bus/__manifest__.py
  cmis_web_bus/models/bus_bus.py
  cmis_web_bus/static/src/cmis_folder/cmis_folder.js
  cmis_web_bus/static/src/cmis_folder/delivery_cmis_service.js
  cmis_web_bus/static/src/js/form_widgets.js
  cmis_web_bus/views/cmis_web_bus.xml
  setup/cmis_web_bus/odoo/addons/cmis_web_bus
  setup/cmis_web_bus/setup.py
Labels: Needs review

#182 [MIG] cmis_web_proxy - Migration to 16.0
  .pre-commit-config.yaml
  cmis_web_proxy/README.rst
  cmis_web_proxy/__manifest__.py
  cmis_web_proxy/controllers/cmis.py
  cmis_web_proxy/models/cmis_backend.py
  cmis_web_proxy/static/src/cmis_folder/cmis_folder.js
  cmis_web_proxy/static/src/cmis_object_wrapper_service.js
  cmis_web_proxy/static/src/js/form_widget.js
  cmis_web_proxy/tests/test_cmis_proxy.py
  cmis_web_proxy/views/cmis_web_proxy.xml
  setup/cmis_web_proxy/odoo/addons/cmis_web_proxy
  setup/cmis_web_proxy/setup.py
Labels: Needs review, approved, stale

#188 [16.0] [FIX] CMIS Backend: form views
  cmis_alf/views/cmis_backend_view.xml
  cmis_field/views/cmis_backend_view.xml
  cmis_web_proxy/views/cmis_backend.xml
  cmis_web_proxy_alf/views/cmis_backend.xml
Labels: Needs review

#180 [16.0] [MIG] cmis_web_report_write - Migration to 16.0
  .pre-commit-config.yaml
  cmis_web_proxy/views/cmis_backend.xml
  cmis_web_report_write/README.rst
  cmis_web_report_write/__manifest__.py
  setup/cmis_web_report_write/odoo/addons/cmis_web_report_write
  setup/cmis_web_report_write/setup.py
Labels: Needs review, stale

#184 [MIG] cmis_web_proxy_alf - Migration to 16.0
  .pre-commit-config.yaml
  cmis_web_proxy_alf/README.rst
  cmis_web_proxy_alf/__manifest__.py
  cmis_web_proxy_alf/controllers/alfresco.py
  cmis_web_proxy_alf/static/src/cmis_folder/cmis_folder.js
  cmis_web_proxy_alf/static/src/cmis_object_wrapper_service.js
  cmis_web_proxy_alf/static/src/js/form_widgets.js
  cmis_web_proxy_alf/views/cmis_web_proxy_alf.xml
  setup/cmis_web_proxy_alf/odoo/addons/cmis_web_proxy_alf
  setup/cmis_web_proxy_alf/setup.py
Labels: approved

#181 [16.0][MIG] cmis_web_report_write_alf - Migration to 16.0
  .pre-commit-config.yaml
  cmis_web_report_write_alf/README.rst
  cmis_web_report_write_alf/__manifest__.py
  cmis_web_report_write_alf/models/ir_actions_report.py
  cmis_web_report_write_alf/static/src/js/cmis_folder.js
  cmis_web_report_write_alf/static/src/js/form_widgets.js
  cmis_web_report_write_alf/views/cmis_web_report_write_alf.xml
  setup/cmis_web_report_write_alf/odoo/addons/cmis_web_report_write_alf
  setup/cmis_web_report_write_alf/setup.py
Labels: stale

#187 [FIX] cmis_report_write: add override to render again to save files in cmis_folder
  cmis_field/__manifest__.py
  cmis_report_write/models/ir_actions_report.py
Labels: Needs review, approved
